# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  hybridrag:
    build:
      args:
        IMAGE_REPO: ${REGISTRY}
        BASE_TAG: ${TAG}
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
      context: ../
      dockerfile: ./Dockerfile
    image: ${REGISTRY:-opea}/hybridrag:${TAG:-latest}
#  hybridrag-ui:
#    build:
#      context: ../ui
#      dockerfile: ./docker/Dockerfile
#    extends: hybridrag
#    image: ${REGISTRY:-opea}/hybridrag-ui:${TAG:-latest}
#  text2cypher:
#    build:
#      context: GenAIComps
#      dockerfile: comps/text2cypher/src/Dockerfile.intel_hpu
#    extends: hybridrag
#    image: ${REGISTRY:-opea}/text2cypher:${TAG:-latest}
